apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: multi-k8s-dev-tls
spec:
  secretName: multi-k8s-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.dev
  dnsNames:
    - multi-k8s.dev
    - www.multi-k8s.dev
